services:
  - type: web
    name: ethara-backend
    env: docker
    dockerfilePath: Backend/Dockerfile
    buildCommand: null
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000

  - type: web
    name: ethara-frontend
    env: docker
    dockerfilePath: Frontend/Dockerfile
    buildCommand: null
    startCommand: serve -s dist -l 3000
