# Alembic Configuration File
# the value of sqlalchemy.url is used for offline mode
sqlalchemy.url = postgresql://postgres:postgres@localhost:5432/inventory

# Python logging's integer levels
sqlalchemy.echo = false
sqlalchemy.echo_pool = false
sqlalchemy.pool_pre_ping = true

# The logging configuration dict is to be here (when set)
[loggers]
keys = sqlalchemy.engine,sqlalchemy.pool,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy.engine]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_sqlalchemy.pool]
level = WARN
handlers =
qualname = sqlalchemy.pool

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
